### ISSUE TITLE
xls-dump.py on an "empty" XLSX file crashes

### ISSUE THREAD

**Issue by bigtonylewis** [LibreOffice/mso-dumper#4]
I created a new empty spreadsheet in Excel Version 1902 (Build 11328.20158 Click-to-Run), and saved it. If I run xls-dump.py on that, it fails:
~~~~~~
$ ~/src/mso-dumper/xls-dump.py --dump-mode=canonical-xml --utf-8 --catch ~/Work/empty.xlsx
Traceback (most recent call last):
File "/home/tony/src/mso-dumper/xls-dump.py", line 241, in
main()
File "/home/tony/src/mso-dumper/xls-dump.py", line 234, in main
dumper.dumpCanonicalXML()
File "/home/tony/src/mso-dumper/xls-dump.py", line 84, in dumpCanonicalXML
dirEntries = self.strm.getDirectoryEntries()
File "/home/tony/src/mso-dumper/msodumper/xlsstream.py", line 406, in getDirectoryEntries
obj = self.getDirectoryObj()
File "/home/tony/src/mso-dumper/msodumper/xlsstream.py", line 392, in getDirectoryObj
self.parseHeader()
File "/home/tony/src/mso-dumper/msodumper/xlsstream.py", line 389, in parseHeader
self.pos = self.header.parse()
File "/home/tony/src/mso-dumper/msodumper/ole.py", line 217, in parse
for i in range(0, n):
File "/usr/lib/python2.7/dist-packages/future/types/newrange.py", line 143, in iter
return range_iterator(self)
File "/usr/lib/python2.7/dist-packages/future/types/newrange.py", line 150, in init
self.stepper = islice(count(range.start, range_.step), len(range_))
~~~~~~
The file is attached.
[empty.xlsx](https://github.com/LibreOffice/mso-dumper/files/2990818/empty.xlsx)

**Comment by ammarfitwalla** [comment]
Can I work on this issue?
